services:
  - type: web
    name: lab-report-processor
    env: python
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
      - key: PORT
        value: "8000"
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true 