services:
  - type: web
    name: lab-report-processor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y tesseract-ocr libgl1-mesa-glx libglib2.0-0
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
      - key: PORT
        value: "8000"
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true 