services:
  - type: web
    name: lab-report-processor
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
      - key: PORT
        value: "8000"
    plan: free
    healthCheckPath: /healthz
    autoDeploy: true
    buildCommand: docker build -t lab-report-processor .
    startCommand: docker run -p $PORT:8000 lab-report-processor 