services:
  - type: web
    name: lab-report-processor
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
    plan: free
    healthCheckPath: /
    autoDeploy: true
    buildCommand: |
      docker build -t lab-report-processor .
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000 