services:
  - type: web
    name: lab-report-processor
    env: python
    buildCommand: |
      pip install -r requirements.txt
      wget https://github.com/tesseract-ocr/tessdata/raw/main/eng.traineddata -O /usr/share/tesseract-ocr/4.00/tessdata/eng.traineddata
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
    plan: free
    healthCheckPath: /
    autoDeploy: true 